/* 
	the format of the tree definition file is simple,
	you can find specification in the Tigra Menu documentation at:
	
	http://www.softcomplex.com/products/tigra_menu/docs/items.html	
*/

var TREE_ITEMS = [
  ['Adium', 'http://www.adiumx.com/',
    ['Core Controllers', '',
      ['Account', 'core/account.html'],
      ['Contact', 'core/contact.html'],
      ['Content', 'core/content.html'],
      ['Interface', 'core/interface.html'],
      ['Login', 'core/login.html'],
      ['Menu', 'core/menu.html'],
      ['Plugin', 'core/plugin.html'],
      ['Preference', 'core/preference.html'],
      ['Sound', 'core/sound.html'],
      ['Toolbar', 'core/toolbar.html'],
    ],
    ['Adium.Framework', '',
      ['AIPlugin', 'adium/plugin.html'],
      ['AIService', 'adium/service.html'],
      ['AIAccount', 'adium/account.html'],
      ['AIServiceType', 'adium/serviceType.html'],
      ['Preference Pane', 'adium/preferencePane.html',
        ['AIPreferenceViewController', 'adium/prefView.html'],
        ['AIContactInfoViewController', 'adium/infoView.html'],
      ],
      ['Contact Object', '',
        ['AIContactObject', 'adium/contactObject.html'],
        ['AIContactGroup', 'adium/contactGroup.html'],
        ['AIContactHandle', 'adium/ContactHandle.html'],
      ],
      ['Content Object', '',
        ['AIContentMessage', 'adium/ContentMessage.html'],
      ],
    ],
    ['AIUtilities.Framework', '',
      ['Interface', '',
        ['Animations', '',
          ['AIAnimatedFloater', ''],
          ['AIAnimatedView', ''],
        ],
        ['Custom Tabs', '',
          ['AICustomTabsView', ''],
          ['AICustomTab', ''],
        ],
        ['Mini Toolbars', '',
          ['AIMiniToolbarCenter', ''],
          ['AIMiniToolbar', ''],
          ['AIMiniToolbarButton', ''],
        ],
        ['AIAlternatingRowOutlineView', ''],
        ['AICompletingTextField', ''],
        ['AIColoredBoxView', ''],
        ['AIImageTextCell', ''],
        ['AISendingTextView', ''],
        ['AIverticallyCenteredTextCell', ''],
      ],
      ['Utilities', '',
        ['Networking', '',
          ['AISocket', ''],
        ],
        ['Images / Drawing', '',
          ['AIImageUtilities', ''],
          ['AIGradient', ''],
        ],
        ['Text / Strings', '',
          ['AITextAttributes', ''],
          ['AIHTMLDecoder', ''],
        ],
        ['Files / Storage / Arrays', '',
          ['AIKeychain', ''],
          ['AIFileUtilities', ''],
          ['AIMutableOwnerArray', ''],
        ],
        ['Interface', '',
          ['AIToolbarUtilities', ''],
          ['AICursorUtilities', ''],
        ],
      ],
      ['Additions', '',
        ['AIAttributedStringAdditions', ''],
        ['AIColorAdditions', ''],
        ['AIScrollViewAdditions', ''],
        ['AIViewAdditions', ''],
        ['AIDictionaryAdditions', ''],
        ['AIMenuAdditions', ''],
        ['AITextFieldAdditions', ''],
      ],
    ],
    ['Plugin Tasks', '',
      ['Creating a plugin', ''],
      ['Service code', ''],
      ['Filtering Text', ''],
      ['Preferences', ''],
      ['Playing Sounds', ''],
      ['Toolbar Buttons', ''],
    ],
    
]];

