// _StatusSortConfiguration_EOArchive_pl.java
// Generated by EnterpriseObjects palette at niedziela, 27 listopada 2005 00:45:48 Europe/Warsaw

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _StatusSortConfiguration_EOArchive_pl extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1;
    com.webobjects.eointerface.swing.EOTable _nsTableView0;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsBox6, _nsBox7, _nsCustomView0;
    javax.swing.JCheckBox _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1, _jRadioButton2, _jRadioButton3;

    public _StatusSortConfiguration_EOArchive_pl(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();


        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_groupMobileSeparately")) != null)) {
            _nsButton6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton6");
        } else {
            _nsButton6 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Grupuj oddzielnie kontakty mobilne"), "NSButton4211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_groupIdleAndAway")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Grupuj kontakty nieaktywne i poza sieci\u0105"), "NSButton44");
        }

        _nsBox7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox112");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "buttonCell_separateUnavailable")) != null)) {
            _jRadioButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton3");
        } else {
            _jRadioButton3 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Grupuj oddzielnie kontakty niedost\u0119pne:"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "buttonCell_allUnavailable")) != null)) {
            _jRadioButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton2");
        } else {
            _jRadioButton2 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Grupuj razem wszystkie kontakty poza sieci\u0105"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "matrix_unavailableGrouping")) != null)) {
            _nsMatrix1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix1");
        } else {
            _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 4, 2), "NSMatrix11");
        }

        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tableView_sortOrder")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox111");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox11");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_alphabeticallyByLastName")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("\u2026 wed\u0142ug nazwiska"), "NSButton43");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_groupAvailable")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Grupuj dost\u0119pne kontakty"), "NSButton421");
        }

        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_groupAway")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Grupuj wszystkie nieobecne kontakty"), "NSButton42");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_groupIdle")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Grupuj wszystkie nieaktywne kontakty"), "NSButton4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "buttonCell_alphabetically")) != null)) {
            _jRadioButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton1");
        } else {
            _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Alfabetycznie"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "buttonCell_manually")) != null)) {
            _jRadioButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton0");
        } else {
            _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("R\u0119cznie"), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "matrix_resolution")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 4, 2), "NSMatrix1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "configureView")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_sortIdleTime")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Sortuj rosn\u0105co wed\u0142ug czasu bezczynno\u015bci"), "NSButton41");
        }
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "checkBox_sortIdleTime");
        }

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _connect(_owner(), _nsButton6, "checkBox_groupMobileSeparately");
        }

        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _nsButton6), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "checkBox_groupIdleAndAway");
        }

        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _connect(_owner(), _nsMatrix1, "matrix_unavailableGrouping");
        }

        _jRadioButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _jRadioButton2), ""));
        _jRadioButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _jRadioButton3), ""));

        if (_replacedObjects.objectForKey("_jRadioButton3") == null) {
            _connect(_owner(), _jRadioButton3, "buttonCell_separateUnavailable");
        }

        if (_replacedObjects.objectForKey("_jRadioButton2") == null) {
            _connect(_owner(), _jRadioButton2, "buttonCell_allUnavailable");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "tableView_sortOrder");
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "checkBox_alphabeticallyByLastName");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "checkBox_groupAvailable");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _nsButton3), ""));

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "checkBox_groupAway");
        }

        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "checkBox_groupIdle");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "matrix_resolution");
        }

        _jRadioButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _jRadioButton0), ""));
        _jRadioButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _jRadioButton1), ""));

        if (_replacedObjects.objectForKey("_jRadioButton1") == null) {
            _connect(_owner(), _jRadioButton1, "buttonCell_alphabetically");
        }

        if (_replacedObjects.objectForKey("_jRadioButton0") == null) {
            _connect(_owner(), _jRadioButton0, "buttonCell_manually");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "configureView");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePreference", _nsButton0), ""));
    }

    protected void _init() {
        super._init();

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _setFontForComponent(_nsButton6, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsBox6.getLayout() instanceof EOViewLayout)) { _nsBox6.setLayout(new EOViewLayout()); }
        _nsBox7.setSize(125, 1);
        _nsBox7.setLocation(2, 2);
        ((EOViewLayout)_nsBox6.getLayout()).setAutosizingMask(_nsBox7, EOViewLayout.MinYMargin);
        _nsBox6.add(_nsBox7);
        _nsBox6.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));

        if (_replacedObjects.objectForKey("_jRadioButton3") == null) {
            _setFontForComponent(_jRadioButton3, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_jRadioButton2") == null) {
            _setFontForComponent(_jRadioButton2, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _jRadioButton2.setSize(328, 17);
            _jRadioButton2.setLocation(0, 0);
            _nsMatrix1.add(_jRadioButton2);
            _jRadioButton3.setSize(328, 18);
            _jRadioButton3.setLocation(0, 20);
            _nsMatrix1.add(_jRadioButton3);
            _setFontForComponent(_nsMatrix1, "Lucida Grande", 13, Font.PLAIN);
        }

        _eoTableColumn0.setMinWidth(8);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(120);
        _eoTableColumn0.setWidth(120);
        _eoTableColumn0.setResizable(false);
        _eoTableColumn0.setHeaderValue("");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(20);
        }

        _connect(_nsTextField1, _nsTableView0, "view_anchorToRightSide");
        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Sortowanie w grupach statusu:");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(125, 1);
        _nsBox5.setLocation(2, 2);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(125, 1);
        _nsBox3.setLocation(2, 2);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(125, 1);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Sortowanie wewn\u0105trz ka\u017cdej grupy statusu:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_jRadioButton1") == null) {
            _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_jRadioButton0") == null) {
            _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jRadioButton0.setSize(259, 17);
            _jRadioButton0.setLocation(0, 0);
            _nsMatrix0.add(_jRadioButton0);
            _jRadioButton1.setSize(259, 18);
            _jRadioButton1.setLocation(0, 20);
            _nsMatrix0.add(_jRadioButton1);
            _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsMatrix0.setSize(260, 38);
            _nsMatrix0.setLocation(37, 236);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsMatrix0);
            _nsButton1.setSize(300, 17);
            _nsButton1.setLocation(37, 136);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton1);
            _nsButton0.setSize(293, 17);
            _nsButton0.setLocation(18, 181);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton0);
            _nsButton2.setSize(293, 17);
            _nsButton2.setLocation(37, 114);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton2);
            _nsTextField0.setSize(280, 17);
            _nsTextField0.setLocation(18, 213);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField0);
            _nsBox0.setSize(274, 5);
            _nsBox0.setLocation(20, 202);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsBox0);
            _nsButton3.setSize(278, 17);
            _nsButton3.setLocation(18, 19);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton3);
            _nsButton4.setSize(241, 17);
            _nsButton4.setLocation(55, 279);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton4);
            _nsBox2.setSize(331, 5);
            _nsBox2.setLocation(20, 202);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsBox2);
            _nsBox4.setSize(331, 5);
            _nsBox4.setLocation(20, 300);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsBox4);
            _nsTextField1.setSize(198, 17);
            _nsTextField1.setLocation(18, 311);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField1);
            _nsTableView0.setSize(125, 78);
            _nsTableView0.setLocation(220, 311);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTableView0);
            _nsMatrix1.setSize(329, 38);
            _nsMatrix1.setLocation(18, 71);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsMatrix1);
            _nsBox6.setSize(331, 5);
            _nsBox6.setLocation(20, 62);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox6, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsBox6);
            _nsButton5.setSize(316, 17);
            _nsButton5.setLocation(37, 158);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton5);
            _nsButton6.setSize(259, 17);
            _nsButton6.setLocation(37, 41);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton6);
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        }
    }
}
