// _ESGaimZephyrAccountView_EOArchive_pl.java
// Generated by EnterpriseObjects palette at niedziela, 27 listopada 2005 00:44:43 Europe/Warsaw

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ESGaimZephyrAccountView_EOArchive_pl extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7;
    com.webobjects.eointerface.swing.EOView _nsCustomView0, _nsCustomView1;
    javax.swing.JCheckBox _nsButton0, _nsButton1;

    public _ESGaimZephyrAccountView_EOArchive_pl(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11321");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1132");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_encoding")) != null)) {
            _nsTextField5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField5");
        } else {
            _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField44142");
        }

        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField113");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_exposure")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField4414");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_exportAnyone")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Eksportuj do .anyone"), "NSButton4111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view_options")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "Options");
        }

        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_accountUID")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField4414");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_accountUIDLabel")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField113");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view_setup")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "setup");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_exportSubs")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Eksportuj do .zephyr.subs"), "NSButton4");
        }
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "checkBox_exportSubs");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_owner(), _nsTextField5, "textField_encoding");
        }

        _nsTextField5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsTextField5), ""));

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "textField_exposure");
        }

        _nsTextField3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsTextField3), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "checkBox_exportAnyone");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_owner(), _nsCustomView1, "view_options");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "textField_accountUID");
        }

        _nsTextField1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsTextField1), ""));

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "textField_accountUIDLabel");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view_setup");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsButton0), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField7, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Eksportuj:");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Kodowanie:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _setFontForComponent(_nsTextField5, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField5.setEditable(true);
            _nsTextField5.setOpaque(true);
            _nsTextField5.setText("");
            _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField5.setSelectable(true);
            _nsTextField5.setEnabled(true);
        }

        _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Ekspozycja:");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField3.setEditable(true);
            _nsTextField3.setOpaque(true);
            _nsTextField3.setText("");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(true);
            _nsTextField3.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
            _nsButton0.setSize(244, 17);
            _nsButton0.setLocation(140, 87);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MaxYMargin);
            _nsCustomView1.add(_nsButton0);
            _nsButton1.setSize(244, 17);
            _nsButton1.setLocation(140, 65);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MaxYMargin);
            _nsCustomView1.add(_nsButton1);
            _nsTextField3.setSize(240, 22);
            _nsTextField3.setLocation(143, 0);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MaxYMargin);
            _nsCustomView1.add(_nsTextField3);
            _nsTextField4.setSize(140, 17);
            _nsTextField4.setLocation(-2, 3);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MaxYMargin);
            _nsCustomView1.add(_nsTextField4);
            _nsTextField5.setSize(240, 22);
            _nsTextField5.setLocation(143, 30);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MaxYMargin);
            _nsCustomView1.add(_nsTextField5);
            _nsTextField6.setSize(140, 17);
            _nsTextField6.setLocation(-2, 33);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MaxYMargin);
            _nsCustomView1.add(_nsTextField6);
            _nsTextField7.setSize(140, 17);
            _nsTextField7.setLocation(-2, 64);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MaxYMargin);
            _nsCustomView1.add(_nsTextField7);
        }

        _setFontForComponent(_nsTextField2, "Lucida Grande", 12, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(true);
        _nsTextField2.setText("Zephyr wymaga, aby by\u0142 uruchomiony poprawnie skonfigurowany Zephyr host manager (zhm), co wi\u0105\u017ce si\u0119 r\u00f3wnie\u017c z poprawn\u0105 konfiguracj\u0105 Kerberos. Zephyr u\u017cywa Twojego UNIX UID lub nazwy Kerberos. Powy\u017csza nazwa u\u017cytkownika s\u0142u\u017cy wy\u0142\u0105cznie do wewn\u0119trznego zastosowania w Adium. Zaleca si\u0119 korzystanie jednocze\u015bnie tylko z jednego po\u0142\u0105czenia Zephyr.");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField0.setEditable(false);
            _nsTextField0.setOpaque(false);
            _nsTextField0.setText("Nazwa u\u017cytkownika:");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField0.setSelectable(false);
            _nsTextField0.setEnabled(true);
            _nsTextField0.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsTextField0.setSize(140, 17);
            _nsTextField0.setLocation(-2, 3);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField0);
            _nsTextField1.setSize(240, 22);
            _nsTextField1.setLocation(143, 0);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField1);
            _nsTextField2.setSize(364, 117);
            _nsTextField2.setLocation(49, 44);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField2);
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        }
    }
}
