/*-------------------------------------------------------------------------------------------------------*\
| Adium, Copyright (C) 2001-2004, Adam Iser  (adamiser@mac.com | http://www.adiumx.com)                   |
\---------------------------------------------------------------------------------------------------------/
 | This program is free software; you can redistribute it and/or modify it under the terms of the GNU
 | General Public License as published by the Free Software Foundation; either version 2 of the License,
 | or (at your option) any later version.
 |
 | This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 | the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 | Public License for more details.
 |
 | You should have received a copy of the GNU General Public License along with this program; if not,
 | write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 \------------------------------------------------------------------------------------------------------ */

#import "AIListObject.h"
#import "AIListGroup.h"

//Uncomment to display ordering information in the contact list
//#define	ORDERING_DEBUG

@interface AIListObject (PRIVATE)
- (NSMutableArray *)_recursivePreferencesForKey:(NSString *)inKey group:(NSString *)groupName;
@end

@implementation AIListObject

DeclareString(ObjectStatusCache);
DeclareString(DisplayName);
DeclareString(LongDisplayName);
DeclareString(Key);
DeclareString(Group);
DeclareString(DisplayServiceID);
DeclareString(FormattedUID);

//Init
- (id)initWithUID:(NSString *)inUID service:(AIService *)inService
{
    [super init];

	InitString(ObjectStatusCache,@"Object Status Cache");
	InitString(DisplayName,@"Display Name");
	InitString(LongDisplayName,@"Long Display Name");
	InitString(Key,@"Key");
	InitString(Group,@"Group");
	InitString(DisplayServiceID,@"DisplayServiceID");
	InitString(FormattedUID,@"FormattedUID");
	
    containingObject = nil;
    UID = [inUID retain];	
	service = inService;
	internalObjectID = nil;
		
	visible = YES;

	//Load the order index for this object (which will be appropriate for the last group it was in)
	NSNumber	*orderIndexNumber = [self preferenceForKey:KEY_ORDER_INDEX
													 group:ObjectStatusCache 
									 ignoreInheritedValues:YES];
	if (orderIndexNumber){
		orderIndex = [orderIndexNumber floatValue];
	}else{
		[self setOrderIndex:[[adium contactController] nextOrderIndex]];
	}
	
    return(self);
}

- (void)dealloc
{	
	//
	[UID release];
	[internalObjectID release];

    [super dealloc];
}


//Identification -------------------------------------------------------------------------------------------------------
#pragma mark Identification
//UID of this object.  For contacts, this is basically the user name.
- (NSString *)UID
{
    return(UID);
}

//Service of this object
- (AIService *)service
{
	return(service);
}

- (NSString *)serviceID
{
	return([service serviceID]);
}
- (NSString *)serviceClass
{
	return([service serviceClass]);
}

//An object ID generated by Adium that is shared by all objects which are, to most intents and purposes, identical to
//this object.  Ths ID is composed of the service ID and UID, so any object with identical services and object ID's
//will have the same value here.
- (NSString *)internalObjectID
{
	if(!internalObjectID){
		internalObjectID = [[AIListObject internalObjectIDForServiceID:[[self service] serviceID] UID:[self UID]] retain];
	}
	return(internalObjectID);
}

+ (NSString *)internalObjectIDForServiceID:(NSString *)inServiceID UID:(NSString *)inUID
{
	return([NSString stringWithFormat:@"%@.%@",inServiceID, inUID]);
}


//Visibility -----------------------------------------------------------------------------------------------------------
#pragma mark Visibility
//Toggle visibility of this object
- (void)setVisible:(BOOL)inVisible
{	
	if(visible != inVisible){
		visible = inVisible;

		if([containingObject isKindOfClass:[AIListGroup class]]){
			//Let our containing group know about the visibility change
			[(AIListGroup *)containingObject visibilityOfContainedObject:self changedTo:inVisible];			
		}
	}
}

//Return current visibility of this object
- (BOOL)visible
{
	return(visible);
}


//Grouping / Ownership -------------------------------------------------------------------------------------------------
#pragma mark Grouping / Ownership
//Return the local group this object is in (will be nil for the root object)
- (AIListObject <AIContainingObject> *)containingObject
{
    return(containingObject);
}

//Set the local grouping for this object (PRIVATE: These are for AIListGroup ONLY)
- (void)setContainingObject:(AIListObject <AIContainingObject> *)inGroup
{
	BOOL hadContainingObject = (containingObject != nil);
	
	containingObject = inGroup;
	
	if (!hadContainingObject){
		//When we get our first containing object, our ordering information is appropriate
		[containingObject listObject:self didSetOrderIndex:orderIndex];
	}else{
		//Otherwise, clear it pending getting new ordering information, putting us the bottom of
		//the containing object for now (but not saving that data)
		orderIndex = ([containingObject largestOrder] + 1.0);

		[containingObject listObject:self didSetOrderIndex:orderIndex];
	}
}

//Returns the group this contact is ultimately within, traversing any other containing objects to find it
- (AIListGroup *)parentGroup
{
	AIListObject	*parentGroup = [[[adium contactController] parentContactForListObject:self] containingObject];
	if (parentGroup && [parentGroup isKindOfClass:[AIListGroup class]]){
		return((AIListGroup *)parentGroup);
	}else{
		return(nil);
	}
}
	
	//Returns our desired placement within a group
- (float)orderIndex
{
	return(orderIndex);
}

//Alter the placement of this object in a group (PRIVATE: These are for AIListGroup ONLY)
- (void)setOrderIndex:(float)inIndex
{
	orderIndex = inIndex;
	[[self containingObject] listObject:self didSetOrderIndex:orderIndex];
	
	//Save it
	[self setPreference:[NSNumber numberWithFloat:orderIndex] forKey:KEY_ORDER_INDEX group:ObjectStatusCache];
	
	//Sort the contained object
//	[[adium contactController] sortListObject:self];
}


//Status objects ------------------------------------------------------------------------------------------------------
#pragma mark Status objects
//
- (void)didModifyStatusKeys:(NSArray *)keys silent:(BOOL)silent
{
	[[adium contactController] listObjectStatusChanged:self
									modifiedStatusKeys:keys
												silent:silent];
}

//When we notify of queued status changes, our containing group should as well as it stays in sync with
//any changes it may have made in object:didSetStatusObject:forKey:notify:
- (void)didNotifyOfChangedStatusSilently:(BOOL)silent
{
	//Let our containing object know about the notification request
	if (containingObject)
		[containingObject notifyOfChangedStatusSilently:silent];
}

//Subclasses may wish to override these - they must be sure to call super's implementation, too!
- (void)object:(id)inObject didSetStatusObject:(id)value forKey:(NSString *)key notify:(NotifyTiming)notify
{				
	//Inform our containing group about the new status object value
	if (containingObject){
		[containingObject object:self didSetStatusObject:value forKey:key notify:notify];
	}
	
	[super object:inObject didSetStatusObject:value forKey:key notify:notify];
}

//AIMutableOwnerArray delegate ------------------------------------------------------------------------------------------
#pragma mark AIMutableOwnerArray delegate

//A mutable owner array (one of our displayArrays) set an object
- (void)mutableOwnerArray:(AIMutableOwnerArray *)inArray didSetObject:(id)anObject withOwner:(id)inOwner priorityLevel:(float)priority
{
	if (containingObject){
		[containingObject listObject:self mutableOwnerArray:inArray didSetObject:anObject withOwner:inOwner priorityLevel:priority];
	}
}

//Empty implementation by default - we do not need to take any action when a mutable owner array changes
- (void)listObject:(AIListObject *)listObject mutableOwnerArray:(AIMutableOwnerArray *)inArray didSetObject:(AIListObject *)anObject withOwner:(AIListObject *)inOwner priorityLevel:(float)priority
{

}

//Object specific preferences ------------------------------------------------------------------------------------------
#pragma mark Object specific preferences
//Set a preference value
- (void)setPreference:(id)value forKey:(NSString *)inKey group:(NSString *)groupName
{   
	NSMutableDictionary	*prefDict = [[adium preferenceController] cachedObjectPrefsForKey:[self internalObjectID]
																					 path:[self pathToPreferences]];

    //Set the new value
    if(value != nil){
		if(!prefDict) prefDict = [[NSMutableDictionary alloc] init];
		[prefDict setObject:value forKey:inKey];
    }else{
        [prefDict removeObjectForKey:inKey];
    }
    
    //Save
	[[adium preferenceController] setCachedObjectPrefs:prefDict
												forKey:[self internalObjectID]
												  path:[self pathToPreferences]];
    
    //Broadcast a preference changed notification
    [[adium notificationCenter] postNotificationName:Preference_GroupChanged
											  object:self
											userInfo:[NSDictionary dictionaryWithObjectsAndKeys:groupName,Group,inKey,Key,nil]];
}

//Retrieve a preference value (with the option of ignoring inherited values)
- (id)preferenceForKey:(NSString *)inKey group:(NSString *)groupName ignoreInheritedValues:(BOOL)ignore
{
	if(!ignore) return([self preferenceForKey:inKey group:groupName]);
	
	//Return our value for the preference only
	NSMutableDictionary	*prefDict = [[adium preferenceController] cachedObjectPrefsForKey:[self internalObjectID]
																					 path:[self pathToPreferences]];
	return([prefDict objectForKey:inKey]);
}

//Retrieve a preference value
- (id)preferenceForKey:(NSString *)inKey group:(NSString *)groupName
{
    id					value = nil;
	NSMutableDictionary	*prefDict = [[adium preferenceController] cachedObjectPrefsForKey:[self internalObjectID]
																					 path:[self pathToPreferences]];

    //Get our value for the preference
    value = [prefDict objectForKey:inKey];
    
    //If we don't have a value
    if(!value){
		if(containingObject){
			//return the value of the group that contains us
			value = [containingObject preferenceForKey:inKey group:groupName];
		}else{
			//If we are the root group, return Adium's global preference for this key
			value = [[adium preferenceController] preferenceForKey:inKey group:groupName];
		}
    }
    
    return(value);
}

//
- (NSArray *)allPreferencesForKey:(NSString *)inKey group:(NSString *)groupName
{
    NSMutableArray *returnArray = [self _recursivePreferencesForKey:inKey group:groupName];
    id      rootValue = [[adium preferenceController] preferenceForKey:inKey group:groupName];
    if (rootValue){
        if (returnArray){
            return [returnArray addObject:rootValue];
        }else{
            return [NSArray arrayWithObject:rootValue];
        }
    }
    
    return returnArray;
}

- (NSMutableArray *)_recursivePreferencesForKey:(NSString *)inKey group:(NSString *)groupName
{
    id					value = nil;
    NSMutableArray  	*returnArray = [NSMutableArray arrayWithCapacity:1];
	NSMutableDictionary	*prefDict = [[adium preferenceController] cachedObjectPrefsForKey:[self internalObjectID]
																					 path:[self pathToPreferences]];
    
    //Get our value for the preference
	if(value = [prefDict objectForKey:inKey]){
		[returnArray addObject:value];
	}
    
    //so long as we aren't the root group, add our containingObjects' preferences
	if(containingObject){
		[returnArray addObjectsFromArray:[containingObject _recursivePreferencesForKey:inKey group:groupName]];
	}
    
    return returnArray;
}

//Path for storing our reference file
- (NSString *)pathToPreferences
{
    return(OBJECT_PREFS_PATH);
}

//Display Name Convenience Methods -------------------------------------------------------------------------------------
#pragma mark Display Name Convenience Methods
/*
 A list object basically has 4 different variations of display.

 - UID, the base UID of the contact "aiser123"
 - formattedUID, formating or alteration of the UID provided by the account code "AIser 123"
 - DisplayName, short formatted name provided by plugins "Adam Iser"
 - LongDisplayName, long formatted name provided by plugins "Adam Iser (AIser 123)"

 A value will always be returned by these methods, so if there is no long display name present it will fall back to
 display name, formattedUID, and finally UID (which is guaranteed to be present).  Use whichever one seems best
 suited for what is being displayed.
 */

//Server-formatted UID if present, otherwise the UID
- (NSString *)formattedUID
{
	NSString  *outName = [self statusObjectForKey:FormattedUID];
    return(outName ? outName : UID);	
}

//Long display name, influenced by plugins
- (NSString *)longDisplayName
{
    NSString	*outName = [[self displayArrayForKey:LongDisplayName] objectValue];
	
#ifndef ORDERING_DEBUG
    return(outName ? outName : [self displayName]);
#else
	return(outName ?
		   [NSString stringWithFormat:@"%@ (%f)",outName,[self orderIndex]] :
		   [NSString stringWithFormat:@"%@ (%f)", [self displayName],[self orderIndex]]);
#endif
}

//- (NSString *)displayServiceID
//{
//	NSString  *outName = [self statusObjectForKey:DisplayServiceID];
//	return (outName ? outName : [serviceType identifier]);
//}

#pragma mark Key-Value Pairing
- (NSImage *)userIcon
{
	return([self displayUserIcon]);
}
- (NSImage *)displayUserIcon
{
	return([[self displayArrayForKey:KEY_USER_ICON create:NO] objectValue]);	
}

- (void)setDisplayUserIcon:(NSImage *)inImage
{
	[self setDisplayUserIcon:inImage withOwner:self priorityLevel:Highest_Priority];
}
- (void)setDisplayUserIcon:(NSImage *)inImage withOwner:(id)inOwner priorityLevel:(float)inPriorityLevel
{
	AIMutableOwnerArray *userIconDisplayArray;
	NSImage				*oldImage;
	
	//If inImage is nil, we don't want to create the display array if it doesn't already exist
	userIconDisplayArray = (inImage ?
							[self displayArrayForKey:KEY_USER_ICON] :
							[self displayArrayForKey:KEY_USER_ICON create:NO]);
	oldImage = [self displayUserIcon];
	
	[[self displayArrayForKey:KEY_USER_ICON] setObject:inImage
											 withOwner:inOwner
										 priorityLevel:inPriorityLevel];
	
	//If the displayUserIcon changed, flush our cache and send out a notification
	if (oldImage != [self displayUserIcon]){
		[AIUserIcons flushCacheForContact:(AIListContact *)self];
		//Notify
		[[adium contactController] listObjectAttributesChanged:self
												  modifiedKeys:[NSArray arrayWithObject:KEY_USER_ICON]];
	}
				
				
}


- (NSData *)userIconData
{
	NSImage *userIcon = [self userIcon];
	return ([userIcon TIFFRepresentation]);
}
- (void)setUserIconData:(NSData *)inData
{
	[self setPreference:inData
				 forKey:KEY_USER_ICON
				  group:PREF_GROUP_USERICONS];
}

- (NSNumber *)idleTime
{
	NSNumber *idleNumber = [self statusObjectForKey:@"Idle"];
	return (idleNumber ? idleNumber : [NSNumber numberWithInt:0]);
}

- (BOOL)online
{
	return ([self integerStatusObjectForKey:@"Online"] ? YES : NO);
}

- (AIStatusSummary)statusSummary
{
	if ([[self numberStatusObjectForKey:@"Online"] boolValue]){
		if ([[self numberStatusObjectForKey:@"Away" fromAnyContainedObject:NO] boolValue]){
			if ([self statusObjectForKey:@"IdleSince" fromAnyContainedObject:NO]){
				return AIAwayAndIdleStatus;
			}else{
				return AIAwayStatus;
			}
			
		}else if ([self statusObjectForKey:@"IdleSince" fromAnyContainedObject:NO]){
			return AIIdleStatus;
			
		}else{
			return AIAvailableStatus;
			
		}
	}else{
		//We don't know the status of an stranger who isn't showing up as online
		if ([[self numberStatusObjectForKey:@"Stranger" fromAnyContainedObject:NO] boolValue]){
			return AIUnknownStatus;
			
		}else{
			return AIOfflineStatus;
			
		}
	}
	
}

- (NSString *)statusMessage
{
	return [[self statusObjectForKey:@"StatusMessage"] string];
}

//Display name, influenced by plugins
- (NSString *)displayName
{
    NSString	*outName = [[self displayArrayForKey:DisplayName] objectValue];
    return(outName ? outName : [self formattedUID]);
}
//Apply an alias
- (void)setDisplayName:(NSString *)alias
{
	if([alias length] == 0) alias = nil; 
	
	NSString	*oldAlias = [self preferenceForKey:@"Alias" group:PREF_GROUP_ALIASES ignoreInheritedValues:YES];
	NSLog(@"Alias: %@ ; oldAlias: %@",alias,oldAlias);
	if ((!alias && oldAlias) ||
		(alias && !([alias isEqualToString:oldAlias]))){
		//Save the alias
		[self setPreference:alias forKey:@"Alias" group:PREF_GROUP_ALIASES];
		
		#warning There must be a cleaner way to do this alias stuff!  This works for now :)
		[[adium notificationCenter] postNotificationName:Contact_ApplyDisplayName
												  object:self
												userInfo:[NSDictionary dictionaryWithObject:[NSNumber numberWithBool:YES]
																					 forKey:@"Notify"]];
	}
}

- (NSString *)notes
{
	NSString *notes;
	
    notes = [self preferenceForKey:@"Notes" group:PREF_GROUP_NOTES ignoreInheritedValues:YES];
	if (!notes) notes = [self statusObjectForKey:@"Notes"];
	
	return notes;
}
- (void)setNotes:(NSString *)notes
{
	if([notes length] == 0) notes = nil; 

	NSString	*oldNotes = [self preferenceForKey:@"Notes" group:PREF_GROUP_NOTES ignoreInheritedValues:YES];
	if ((!notes && oldNotes) ||
		(notes && (![notes isEqualToString:oldNotes]))){
		//Save the note
		[self setPreference:notes forKey:@"Notes" group:PREF_GROUP_NOTES];
	}
}

- (NSComparisonResult)compare:(id)otherObject
{
	return ([otherObject isKindOfClass:[self class]] &&
			[[self internalObjectID] caseInsensitiveCompare:[otherObject internalObjectID]]);
}

#pragma mark Debugging
- (NSString *)description
{
	return [NSString stringWithFormat:@"%@:%@",[super description],[self internalObjectID]];
}

//Contained Contacts (should be subclassed) ----------------------------------------------------------------------------
//#pragma mark Contained Contacts (Subclassed)
//- (BOOL)addObject:(AIListObject *)inObject { return NO; };
//- (void)removeObject:(AIListObject *)inObject {};
//- (void)visibilityOfContainedObject:(AIListObject *)inObject changedTo:(BOOL)inVisible {};
//- (void)sortListObject:(AIListObject *)inObject sortController:(AISortController *)sortController {};

//Contained Contacts (handled for subclasses) --------------------------------------------------------------------------
//All these methods will have no effect, returning 0 or nil as appropriate, for non-subclassed AIListObject
#pragma mark Contained Contacts (Handled for subclasses)
//
//// Return an array of all objects. Defaults to just ourself.
//- (NSArray *)listContacts
//{
//	return [NSArray arrayWithObject:self];
//}
//


@end
