// _ESGaimNovellAccountView_EOArchive_pl.java
// Generated by EnterpriseObjects palette at niedziela, 27 listopada 2005 00:44:30 Europe/Warsaw

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ESGaimNovellAccountView_EOArchive_pl extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6;
    com.webobjects.eointerface.swing.EOView _nsCustomView0;
    javax.swing.JPasswordField _nsTextField7;

    public _ESGaimNovellAccountView_EOArchive_pl(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();


        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_connectPort")) != null)) {
            _nsTextField6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField6");
        } else {
            _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField441111");
        }

        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11111");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_connectHost")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField44111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_password")) != null)) {
            _nsTextField7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JPasswordField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField7");
        } else {
            _nsTextField7 = (javax.swing.JPasswordField)_registered(new javax.swing.JPasswordField(), "NSTextField4411");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_accountUIDLabel")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view_options")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "Setup");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_accountUID")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField441");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "textField_accountUID");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view_options");
        }

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _connect(_owner(), _nsTextField6, "textField_connectPort");
        }

        _nsTextField6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsTextField6), ""));

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "textField_connectHost");
        }

        _nsTextField3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsTextField3), ""));

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _connect(_owner(), _nsTextField7, "textField_password");
        }

        _nsTextField7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsTextField7), ""));

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "textField_accountUIDLabel");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view_setup");
        }

        _nsTextField1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changedPreference", _nsTextField1), ""));
    }

    protected void _init() {
        super._init();

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _setFontForComponent(_nsTextField6, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField6.setEditable(true);
            _nsTextField6.setOpaque(true);
            _nsTextField6.setText("");
            _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField6.setSelectable(true);
            _nsTextField6.setEnabled(true);
        }

        _setFontForComponent(_nsTextField5, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("Port:");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Serwer:");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField3.setEditable(true);
            _nsTextField3.setOpaque(true);
            _nsTextField3.setText("");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(true);
            _nsTextField3.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _setFontForComponent(_nsTextField7, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField7.setEditable(true);
            _nsTextField7.setOpaque(true);
            _nsTextField7.setText("");
            _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField7.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField2.setEditable(false);
            _nsTextField2.setOpaque(false);
            _nsTextField2.setText("Nazwa u\u017cytkownika:");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
            _nsTextField2.setSelectable(false);
            _nsTextField2.setEnabled(true);
            _nsTextField2.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsTextField1.setSize(206, 22);
            _nsTextField1.setLocation(143, 0);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField1);
            _nsTextField2.setSize(140, 17);
            _nsTextField2.setLocation(-2, 3);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField2);
            _nsTextField0.setSize(140, 17);
            _nsTextField0.setLocation(-2, 63);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField0);
            _nsTextField7.setSize(206, 22);
            _nsTextField7.setLocation(143, 60);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField7);
            _nsTextField3.setSize(206, 22);
            _nsTextField3.setLocation(143, 30);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField3);
            _nsTextField4.setSize(140, 17);
            _nsTextField4.setLocation(-2, 33);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField4);
            _nsTextField5.setSize(34, 17);
            _nsTextField5.setLocation(354, 33);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField5);
            _nsTextField6.setSize(50, 22);
            _nsTextField6.setLocation(393, 30);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField6);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Has\u0142o:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
    }
}
