// _DCGaimJabberJoinChatView_EOArchive_pl.java
// Generated by EnterpriseObjects palette at niedziela, 27 listopada 2005 00:43:50 Europe/Warsaw

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _DCGaimJabberJoinChatView_EOArchive_pl extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsCustomView0;
    javax.swing.JPasswordField _nsTextField12;

    public _DCGaimJabberJoinChatView_EOArchive_pl(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField212");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2112");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField112");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_handle.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField5");
        } else {
            _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view.nextFocusableComponent")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_handle.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField31");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_handle.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField3");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_handle.nextFocusableComponent")) != null)) {
            _nsTextField12 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JPasswordField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField12");
        } else {
            _nsTextField12 = (javax.swing.JPasswordField)_registered(new javax.swing.JPasswordField(), "NSTextField111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_handle.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2111");
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _connect(_nsTextField12, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_nsTextField1, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_nsTextField4, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "textField_inviteMessage");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "textField_inviteUsers");
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _connect(_owner(), _nsTextField12, "textField_password");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "textField_handle");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_owner(), _nsTextField5, "textField_server");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "textField_roomName");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_nsTextField5, _owner(), "delegate");
        }
    }

    protected void _init() {
        super._init();

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_nsCustomView0, _nsTextField4, "nextFocusableComponent");
        }

        _setFontForComponent(_nsTextField11, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField11.setEditable(false);
        _nsTextField11.setOpaque(false);
        _nsTextField11.setText("Do\u0142\u0105cz wiadomo\u015b\u0107:");
        _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField11.setSelectable(false);
        _nsTextField11.setEnabled(true);
        _nsTextField11.setBorder(null);
        _setFontForComponent(_nsTextField10, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("Zapro\u015b kontakty:");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);
        _setFontForComponent(_nsTextField9, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField9.setEditable(false);
        _nsTextField9.setOpaque(false);
        _nsTextField9.setText("Oddziel nazwy kontakt\u00f3w przecinkami.");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField9.setSelectable(false);
        _nsTextField9.setEnabled(true);
        _nsTextField9.setBorder(null);
        _setFontForComponent(_nsTextField8, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("Identyfikator:");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Serwer:");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Pok\u00f3j pogaw\u0119dek:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsTextField4.setSize(266, 22);
            _nsTextField4.setLocation(123, 0);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField4);
            _nsTextField6.setSize(120, 17);
            _nsTextField6.setLocation(-2, 0);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField6);
            _nsTextField5.setSize(266, 22);
            _nsTextField5.setLocation(123, 30);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField5);
            _nsTextField7.setSize(120, 17);
            _nsTextField7.setLocation(-2, 30);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField7);
            _nsTextField1.setSize(266, 22);
            _nsTextField1.setLocation(123, 60);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField1);
            _nsTextField8.setSize(120, 17);
            _nsTextField8.setLocation(-2, 60);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField8);
            _nsTextField12.setSize(266, 22);
            _nsTextField12.setLocation(123, 90);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField12);
            _nsTextField0.setSize(120, 17);
            _nsTextField0.setLocation(-2, 90);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField0);
            _nsTextField9.setSize(224, 14);
            _nsTextField9.setLocation(120, 179);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField9);
            _nsTextField10.setSize(120, 17);
            _nsTextField10.setLocation(-2, 123);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField10);
            _nsTextField2.setSize(266, 60);
            _nsTextField2.setLocation(123, 120);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField2);
            _nsTextField11.setSize(120, 34);
            _nsTextField11.setLocation(-2, 201);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField11);
            _nsTextField3.setSize(266, 60);
            _nsTextField3.setLocation(123, 198);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField3);
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_nsTextField5, _nsTextField1, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _setFontForComponent(_nsTextField5, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField5.setEditable(true);
            _nsTextField5.setOpaque(true);
            _nsTextField5.setText("");
            _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField5.setSelectable(true);
            _nsTextField5.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_nsTextField4, _nsTextField5, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField4.setEditable(true);
            _nsTextField4.setOpaque(true);
            _nsTextField4.setText("");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(true);
            _nsTextField4.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_nsTextField3, _nsTextField4, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField3.setEditable(true);
            _nsTextField3.setOpaque(true);
            _nsTextField3.setText("");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(true);
            _nsTextField3.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_nsTextField2, _nsTextField3, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField2.setEditable(true);
            _nsTextField2.setOpaque(true);
            _nsTextField2.setText("");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField2.setSelectable(true);
            _nsTextField2.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _connect(_nsTextField12, _nsTextField2, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _setFontForComponent(_nsTextField12, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField12.setEditable(true);
            _nsTextField12.setOpaque(true);
            _nsTextField12.setText("");
            _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField12.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_nsTextField1, _nsTextField12, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Has\u0142o:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
    }
}
