/* These strings are no longer used in HEAD but are still needed in 0.8x.  If you delete a string from HEAD,
 * but not from 0.8x, move it here so genstrings continues to put it in our Localizable.strings.
 *
 * This file goes when 0.90 is released.
 */

AILocalizedString(@"Sorry, but Adium Message Styles are not supported in OS X 10.2 (Jaguar).", nil)
AILocalizedString(@"Sort tabs with the current sort options",nil)
AILocalizedString(@"Remove %@",nil)
AILocalizedString(@"Remove %@ from your list?",nil)
AILocalizedString(@"Be careful. You cannot undo this action.",nil)
AILocalizedString(@"Order the contact list:",nil)
AILocalizedString(@"Hide while Adium is in the background",nil)
AILocalizedString(@"Add to Accounts:",nil)
AILocalizedString(@"Group Name:",nil)
AILocalizedString(@"Messages send on:",nil)
AILocalizedString(@"Send on Enter",nil)
AILocalizedString(@"Send on Return",nil)
AILocalizedString(@"Save As",nil)
AILocalizedString(@"Initiating file transfer...",nil)
AILocalizedString(@"Accepted file transfer...",nil)
AILocalizedString(@"Initializing transfer...",nil)
AILocalizedString(@"Other...",nil)
AILocalizedString(@"Preferences...",nil)
AILocalizedString(@"Save As...",nil)
AILocalizedString(@"Page Setup...",nil)
AILocalizedString(@"Print...",nil)
AILocalizedString(@"Customize Toolbar...",nil)
AILocalizedString(@"Configure Sorting...",nil)
AILocalizedString(@"Browse...",nil)
AILocalizedString(@"Add New Layout...",nil)
AILocalizedString(@"Edit Layouts...",nil)
AILocalizedString(@"Add New Theme...",nil)
AILocalizedString(@"Edit Themes...",nil)
AILocalizedString(@"New Chat...",nil)
AILocalizedString(@"Edit Status Menu...",nil)
AILocalizedString(@"Check for Updates...",nil)
AILocalizedString(@"Add New Preset...",nil)
AILocalizedString(@"Edit Presets...",nil)
AILocalizedString(@"Add Link...",nil)
AILocalizedString(@"Edit Link...",nil)
AILocalizedString(@"Opening logs...",nil)
AILocalizedString(@"Show Details...",nil)
AILocalizedString(@"About Encryption...",nil)
AILocalizedString(@"Join Group Chat...",nil)
AILocalizedString(@"Custom...","Title of the Custom Message Style popup menu item")
AILocalizedString(@"Please wait...",nil)
AILocalizedString(@"Restore Default Formatting",nil)
AILocalizedString(@"Play through default device",nil)
AILocalizedString(@"Play through alert device",nil)
AILocalizedString(@"Sound:",nil)
AILocalizedString(@"Adium was updated on %@. Your copy is %@ old.  Would you like to update?", nil)
AILocalizedString(@"Check for updates automatically", nil)
AILocalizedString(@"Your Adium is up to date",nil)
AILocalizedString(@"No updates are available.  Please try again later.",nil)
AILocalizedString(@"Check for Updates...",nil)
AILocalizedString(@"Consolidate contacts listed in the card",nil)
AILocalizedString(@"%i contacts",nil)
AILocalizedString(@"Paste Formatted",nil)
AILocalizedString(@"Automatically connect on launch","Accounts preferences: When Adium loads, connect this account immediately.")
