// _ListThemeSheet_EOArchive_pl.java
// Generated by EnterpriseObjects palette at niedziela, 27 listopada 2005 00:45:27 Europe/Warsaw

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ListThemeSheet_EOArchive_pl extends com.webobjects.eoapplication.EOArchive {
    AITextColorPreviewView _nsCustomView0, _nsCustomView1, _nsCustomView10, _nsCustomView11, _nsCustomView2, _nsCustomView3, _nsCustomView4, _nsCustomView5, _nsCustomView6, _nsCustomView7, _nsCustomView8, _nsCustomView9;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8;
    com.webobjects.eointerface.swing.EOView _nsColorWell0, _nsColorWell1, _nsColorWell10, _nsColorWell11, _nsColorWell12, _nsColorWell13, _nsColorWell14, _nsColorWell15, _nsColorWell16, _nsColorWell17, _nsColorWell18, _nsColorWell19, _nsColorWell2, _nsColorWell20, _nsColorWell21, _nsColorWell22, _nsColorWell23, _nsColorWell24, _nsColorWell3, _nsColorWell4, _nsColorWell5, _nsColorWell6, _nsColorWell7, _nsColorWell8, _nsColorWell9, _nsSlider0, _nsView0, _nsView1, _nsView2, _nsView3;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2;
    javax.swing.JCheckBox _nsButton10, _nsButton11, _nsButton12, _nsButton13, _nsButton14, _nsButton15, _nsButton16, _nsButton17, _nsButton18, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8, _nsButton9;
    javax.swing.JComboBox _popup0;
    javax.swing.JPanel _nsView4;
    javax.swing.JTabbedPane _nsTabView0;

    public _ListThemeSheet_EOArchive_pl(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211112");
        _nsView3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2211111");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211112");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField221111");
        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Gotowe"), "NSButton2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "popUp_displayImageStyle")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_groupShadow")) != null)) {
            _nsButton18 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton18");
        } else {
            _nsButton18 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Tekst cieniowany"), "NSButton41");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_backgroundAsEvents")) != null)) {
            _nsButton17 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton17");
        } else {
            _nsButton17 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Kolorowe t\u0142a"), "NSButton432");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_unviewedContent.backgroundColor")) != null)) {
            _nsColorWell24 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell24");
        } else {
            _nsColorWell24 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121133");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_unviewedContent")) != null)) {
            _nsCustomView11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView11");
        } else {
            _nsCustomView11 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View233");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_unviewedContent.textColor")) != null)) {
            _nsColorWell23 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell23");
        } else {
            _nsColorWell23 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21112112113111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_typing.backgroundColor")) != null)) {
            _nsColorWell22 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell22");
        } else {
            _nsColorWell22 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211211321");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_typing")) != null)) {
            _nsCustomView10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView10");
        } else {
            _nsCustomView10 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View232");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_typing.textColor")) != null)) {
            _nsColorWell21 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell21");
        } else {
            _nsColorWell21 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211211312");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_signedOff.backgroundColor")) != null)) {
            _nsColorWell20 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell20");
        } else {
            _nsColorWell20 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211212");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_signedOff")) != null)) {
            _nsCustomView9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView9");
        } else {
            _nsCustomView9 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View21");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_signedOff.textColor")) != null)) {
            _nsColorWell19 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell19");
        } else {
            _nsColorWell19 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21112112132");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_signedOn.backgroundColor")) != null)) {
            _nsColorWell18 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell18");
        } else {
            _nsColorWell18 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21112112112");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_signedOn")) != null)) {
            _nsCustomView8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView8");
        } else {
            _nsCustomView8 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View2");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_signedOn.textColor")) != null)) {
            _nsColorWell17 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell17");
        } else {
            _nsColorWell17 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121142");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_grid")) != null)) {
            _nsCustomView7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView7");
        } else {
            _nsCustomView7 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_grid.backgroundColor")) != null)) {
            _nsColorWell16 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell16");
        } else {
            _nsColorWell16 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121131111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_background")) != null)) {
            _nsCustomView6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView6");
        } else {
            _nsCustomView6 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_background.backgroundColor")) != null)) {
            _nsColorWell15 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell15");
        } else {
            _nsColorWell15 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21112112114");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_unviewedContent")) != null)) {
            _nsButton16 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton16");
        } else {
            _nsButton16 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Nieprzeczytane wiadomo\u015bci"), "NSButton4211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_typing")) != null)) {
            _nsButton15 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton15");
        } else {
            _nsButton15 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Pisze"), "NSButton422");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_signedOn")) != null)) {
            _nsButton14 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton14");
        } else {
            _nsButton14 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Zalogowa\u0142 si\u0119"), "NSButton44");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_signedOff")) != null)) {
            _nsButton13 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton13");
        } else {
            _nsButton13 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Wylogowa\u0142 si\u0119"), "NSButton412");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_groupGradient")) != null)) {
            _nsButton12 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton12");
        } else {
            _nsButton12 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("T\u0142o"), "NSButton411");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_drawGrid")) != null)) {
            _nsButton11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton11");
        } else {
            _nsButton11 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Co drugi wiersz"), "NSButton42111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_fadeOfflineImages")) != null)) {
            _nsButton10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton10");
        } else {
            _nsButton10 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Wygaszaj znaczki kontakt\u00f3w poza sieci\u0105"), "NSButton431");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "colorWell_statusText")) != null)) {
            _nsColorWell14 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell14");
        } else {
            _nsColorWell14 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121131112");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_backgroundAsStatus")) != null)) {
            _nsButton9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton9");
        } else {
            _nsButton9 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Kolorowe t\u0142a"), "NSButton43");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_group.textShadowColor")) != null)) {
            _nsColorWell13 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell13");
        } else {
            _nsColorWell13 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211211111211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_group.backgroundGradientColor")) != null)) {
            _nsColorWell12 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell12");
        } else {
            _nsColorWell12 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21112112111111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_group.textColor")) != null)) {
            _nsColorWell11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell11");
        } else {
            _nsColorWell11 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121111121");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_group")) != null)) {
            _nsCustomView5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView5");
        } else {
            _nsCustomView5 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View2331");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_group.backgroundColor")) != null)) {
            _nsColorWell10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell10");
        } else {
            _nsColorWell10 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211211111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_backgroundFade")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "slider_backgroundFade")) != null)) {
            _nsSlider0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSlider0");
        } else {
            _nsSlider0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSSlider21");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textField_backgroundImagePath")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "button_setBackgroundImage")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Wybierz\u2026"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_useBackgroundImage")) != null)) {
            _nsButton8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton8");
        } else {
            _nsButton8 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Obrazek t\u0142a"), "NSButton4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_idleAndAway.backgroundColor")) != null)) {
            _nsColorWell9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell9");
        } else {
            _nsColorWell9 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21112112113");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_idleAndAway")) != null)) {
            _nsCustomView4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView4");
        } else {
            _nsCustomView4 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View231");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_idleAndAway.textColor")) != null)) {
            _nsColorWell8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell8");
        } else {
            _nsColorWell8 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211211311");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_away.backgroundColor")) != null)) {
            _nsColorWell7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell7");
        } else {
            _nsColorWell7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121132");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_away")) != null)) {
            _nsCustomView3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView3");
        } else {
            _nsCustomView3 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View23");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_away.textColor")) != null)) {
            _nsColorWell6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell6");
        } else {
            _nsColorWell6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121131");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_idle.backgroundColor")) != null)) {
            _nsColorWell5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell5");
        } else {
            _nsColorWell5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_idle")) != null)) {
            _nsCustomView2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView2");
        } else {
            _nsCustomView2 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View22");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_idle.textColor")) != null)) {
            _nsColorWell4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell4");
        } else {
            _nsColorWell4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211213");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_offline.backgroundColor")) != null)) {
            _nsColorWell3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell3");
        } else {
            _nsColorWell3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211211331");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_offline")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_offline.textColor")) != null)) {
            _nsColorWell2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell2");
        } else {
            _nsColorWell2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "211121121131111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_online.backgroundColor")) != null)) {
            _nsColorWell1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell1");
        } else {
            _nsColorWell1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2111211211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_online")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (AITextColorPreviewView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (AITextColorPreviewView)_registered(new AITextColorPreviewView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "preview_online.textColor")) != null)) {
            _nsColorWell0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell0");
        } else {
            _nsColorWell0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21112112114");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_idleAndAway")) != null)) {
            _nsButton7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton7");
        } else {
            _nsButton7 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Nieaktywni i nieobecni"), "NSButton421");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_away")) != null)) {
            _nsButton6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton6");
        } else {
            _nsButton6 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Nieobecny"), "NSButton42");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_idle")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Nieaktywny"), "NSButton41");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_offline")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Poza sieci\u0105"), "NSButton42111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "checkBox_online")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Dost\u0119pny"), "NSButton4");
        }

        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Poniechaj"), "NSButton1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel");
        }

        _nsView4 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "okay", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_eoFrame0, _owner(), "delegate");
        }

        _popup0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _popup0), ""));

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Item3");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "popUp_displayImageStyle");
        }

        _nsButton18.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton18), ""));

        if (_replacedObjects.objectForKey("_nsButton18") == null) {
            _connect(_owner(), _nsButton18, "checkBox_groupShadow");
        }

        _nsButton17.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton17), ""));

        if (_replacedObjects.objectForKey("_nsButton17") == null) {
            _connect(_owner(), _nsButton17, "checkBox_backgroundAsEvents");
        }

        if (_replacedObjects.objectForKey("_nsCustomView11") == null) {
            _connect(_owner(), _nsCustomView11, "preview_unviewedContent");
        }

        if (_replacedObjects.objectForKey("_nsColorWell24") == null) {
            _connect(_owner(), _nsColorWell24, "colorWell_unviewedContentLabel");
        }

        _nsColorWell24.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell24), ""));
        _nsColorWell23.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell23), ""));

        if (_replacedObjects.objectForKey("_nsColorWell23") == null) {
            _connect(_owner(), _nsColorWell23, "colorWell_unviewedContent");
        }

        if (_replacedObjects.objectForKey("_nsCustomView10") == null) {
            _connect(_owner(), _nsCustomView10, "preview_typing");
        }

        if (_replacedObjects.objectForKey("_nsColorWell22") == null) {
            _connect(_owner(), _nsColorWell22, "colorWell_typingLabel");
        }

        _nsColorWell22.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell22), ""));
        _nsColorWell21.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell21), ""));

        if (_replacedObjects.objectForKey("_nsColorWell21") == null) {
            _connect(_owner(), _nsColorWell21, "colorWell_typing");
        }

        if (_replacedObjects.objectForKey("_nsCustomView9") == null) {
            _connect(_owner(), _nsCustomView9, "preview_signedOff");
        }

        if (_replacedObjects.objectForKey("_nsColorWell20") == null) {
            _connect(_owner(), _nsColorWell20, "colorWell_signedOffLabel");
        }

        _nsColorWell20.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell20), ""));
        _nsColorWell19.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell19), ""));

        if (_replacedObjects.objectForKey("_nsColorWell19") == null) {
            _connect(_owner(), _nsColorWell19, "colorWell_signedOff");
        }

        if (_replacedObjects.objectForKey("_nsCustomView8") == null) {
            _connect(_owner(), _nsCustomView8, "preview_signedOn");
        }

        if (_replacedObjects.objectForKey("_nsColorWell18") == null) {
            _connect(_owner(), _nsColorWell18, "colorWell_signedOnLabel");
        }

        _nsColorWell18.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell18), ""));
        _nsColorWell17.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell17), ""));

        if (_replacedObjects.objectForKey("_nsColorWell17") == null) {
            _connect(_owner(), _nsColorWell17, "colorWell_signedOn");
        }

        if (_replacedObjects.objectForKey("_nsCustomView7") == null) {
            _connect(_owner(), _nsCustomView7, "preview_grid");
        }

        _nsColorWell16.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell16), ""));

        if (_replacedObjects.objectForKey("_nsColorWell16") == null) {
            _connect(_owner(), _nsColorWell16, "colorWell_grid");
        }

        if (_replacedObjects.objectForKey("_nsCustomView6") == null) {
            _connect(_owner(), _nsCustomView6, "preview_background");
        }

        _nsColorWell15.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell15), ""));

        if (_replacedObjects.objectForKey("_nsColorWell15") == null) {
            _connect(_owner(), _nsColorWell15, "colorWell_background");
        }

        _nsButton16.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton16), ""));

        if (_replacedObjects.objectForKey("_nsButton16") == null) {
            _connect(_owner(), _nsButton16, "checkBox_unviewedContent");
        }

        _nsButton15.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton15), ""));

        if (_replacedObjects.objectForKey("_nsButton15") == null) {
            _connect(_owner(), _nsButton15, "checkBox_typing");
        }

        _nsButton14.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton14), ""));

        if (_replacedObjects.objectForKey("_nsButton14") == null) {
            _connect(_owner(), _nsButton14, "checkBox_signedOn");
        }

        _nsButton13.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton13), ""));

        if (_replacedObjects.objectForKey("_nsButton13") == null) {
            _connect(_owner(), _nsButton13, "checkBox_signedOff");
        }

        _nsButton12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton12), ""));

        if (_replacedObjects.objectForKey("_nsButton12") == null) {
            _connect(_owner(), _nsButton12, "checkBox_groupGradient");
        }

        _nsButton11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton11), ""));

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _connect(_owner(), _nsButton11, "checkBox_drawGrid");
        }

        _nsButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton10), ""));

        if (_replacedObjects.objectForKey("_nsButton10") == null) {
            _connect(_owner(), _nsButton10, "checkBox_fadeOfflineImages");
        }

        _nsColorWell14.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell14), ""));

        if (_replacedObjects.objectForKey("_nsColorWell14") == null) {
            _connect(_owner(), _nsColorWell14, "colorWell_statusText");
        }

        _nsButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton9), ""));

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _connect(_owner(), _nsButton9, "checkBox_backgroundAsStatus");
        }

        if (_replacedObjects.objectForKey("_nsCustomView5") == null) {
            _connect(_owner(), _nsCustomView5, "preview_group");
        }

        if (_replacedObjects.objectForKey("_nsColorWell13") == null) {
            _connect(_owner(), _nsColorWell13, "colorWell_groupShadow");
        }

        _nsColorWell13.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell13), ""));

        if (_replacedObjects.objectForKey("_nsColorWell12") == null) {
            _connect(_owner(), _nsColorWell12, "colorWell_groupBackgroundGradient");
        }

        _nsColorWell12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell12), ""));

        if (_replacedObjects.objectForKey("_nsColorWell11") == null) {
            _connect(_owner(), _nsColorWell11, "colorWell_groupText");
        }

        _nsColorWell11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell11), ""));
        _nsColorWell10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell10), ""));

        if (_replacedObjects.objectForKey("_nsColorWell10") == null) {
            _connect(_owner(), _nsColorWell10, "colorWell_groupBackground");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "textField_backgroundFade");
        }

        _nsSlider0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsSlider0), ""));

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _connect(_owner(), _nsSlider0, "slider_backgroundFade");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "textField_backgroundImagePath");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectBackgroundImage", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "button_setBackgroundImage");
        }

        _nsButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton8), ""));

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _connect(_owner(), _nsButton8, "checkBox_useBackgroundImage");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_nsCustomView4") == null) {
            _connect(_owner(), _nsCustomView4, "preview_idleAndAway");
        }

        if (_replacedObjects.objectForKey("_nsColorWell9") == null) {
            _connect(_owner(), _nsColorWell9, "colorWell_idleAndAwayLabel");
        }

        _nsColorWell9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell9), ""));
        _nsColorWell8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell8), ""));

        if (_replacedObjects.objectForKey("_nsColorWell8") == null) {
            _connect(_owner(), _nsColorWell8, "colorWell_idleAndAway");
        }

        if (_replacedObjects.objectForKey("_nsCustomView3") == null) {
            _connect(_owner(), _nsCustomView3, "preview_away");
        }

        if (_replacedObjects.objectForKey("_nsColorWell7") == null) {
            _connect(_owner(), _nsColorWell7, "colorWell_awayLabel");
        }

        _nsColorWell7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell7), ""));
        _nsColorWell6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell6), ""));

        if (_replacedObjects.objectForKey("_nsColorWell6") == null) {
            _connect(_owner(), _nsColorWell6, "colorWell_away");
        }

        if (_replacedObjects.objectForKey("_nsCustomView2") == null) {
            _connect(_owner(), _nsCustomView2, "preview_idle");
        }

        if (_replacedObjects.objectForKey("_nsColorWell5") == null) {
            _connect(_owner(), _nsColorWell5, "colorWell_idleLabel");
        }

        _nsColorWell5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell5), ""));
        _nsColorWell4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell4), ""));

        if (_replacedObjects.objectForKey("_nsColorWell4") == null) {
            _connect(_owner(), _nsColorWell4, "colorWell_idle");
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_owner(), _nsCustomView1, "preview_offline");
        }

        if (_replacedObjects.objectForKey("_nsColorWell3") == null) {
            _connect(_owner(), _nsColorWell3, "colorWell_offlineLabel");
        }

        _nsColorWell3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell3), ""));
        _nsColorWell2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell2), ""));

        if (_replacedObjects.objectForKey("_nsColorWell2") == null) {
            _connect(_owner(), _nsColorWell2, "colorWell_offline");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "preview_online");
        }

        if (_replacedObjects.objectForKey("_nsColorWell1") == null) {
            _connect(_owner(), _nsColorWell1, "colorWell_onlineLabel");
        }

        _nsColorWell1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell1), ""));
        _nsColorWell0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsColorWell0), ""));

        if (_replacedObjects.objectForKey("_nsColorWell0") == null) {
            _connect(_owner(), _nsColorWell0, "colorWell_online");
        }

        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton7), ""));

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _connect(_owner(), _nsButton7, "checkBox_idleAndAway");
        }

        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton6), ""));

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _connect(_owner(), _nsButton6, "checkBox_away");
        }

        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "checkBox_idle");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "checkBox_offline");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "preferenceChanged", _nsButton3), ""));

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "checkBox_online");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "cancel", _nsButton0), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField8, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("do");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Kolor tekstu");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsColorWell12.setSize(30, 20);
        _nsColorWell12.setLocation(232, 65);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsColorWell12, EOViewLayout.MinYMargin);
        _nsView3.add(_nsColorWell12);
        _nsColorWell10.setSize(30, 20);
        _nsColorWell10.setLocation(174, 65);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsColorWell10, EOViewLayout.MinYMargin);
        _nsView3.add(_nsColorWell10);
        _nsColorWell11.setSize(30, 20);
        _nsColorWell11.setLocation(174, 21);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsColorWell11, EOViewLayout.MinYMargin);
        _nsView3.add(_nsColorWell11);
        _nsTextField7.setSize(118, 17);
        _nsTextField7.setLocation(40, 23);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField7);
        _nsCustomView5.setSize(133, 22);
        _nsCustomView5.setLocation(258, 20);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsCustomView5, EOViewLayout.MinYMargin);
        _nsView3.add(_nsCustomView5);
        _nsButton18.setSize(153, 17);
        _nsButton18.setLocation(21, 46);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton18, EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton18);
        _nsButton12.setSize(154, 17);
        _nsButton12.setLocation(21, 68);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsButton12, EOViewLayout.MinYMargin);
        _nsView3.add(_nsButton12);
        _nsColorWell13.setSize(30, 20);
        _nsColorWell13.setLocation(174, 43);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsColorWell13, EOViewLayout.MinYMargin);
        _nsView3.add(_nsColorWell13);
        _nsTextField8.setSize(18, 14);
        _nsTextField8.setLocation(210, 68);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
        _nsView3.add(_nsTextField8);
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsColorWell20.setSize(30, 20);
        _nsColorWell20.setLocation(263, 44);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsColorWell20, EOViewLayout.MinYMargin);
        _nsView2.add(_nsColorWell20);
        _nsButton14.setSize(143, 17);
        _nsButton14.setLocation(21, 24);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton14, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton14);
        _nsColorWell18.setSize(30, 20);
        _nsColorWell18.setLocation(263, 22);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsColorWell18, EOViewLayout.MinYMargin);
        _nsView2.add(_nsColorWell18);
        _nsButton16.setSize(198, 17);
        _nsButton16.setLocation(21, 90);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton16, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton16);
        _nsColorWell19.setSize(30, 20);
        _nsColorWell19.setLocation(225, 44);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsColorWell19, EOViewLayout.MinYMargin);
        _nsView2.add(_nsColorWell19);
        _nsColorWell21.setSize(30, 20);
        _nsColorWell21.setLocation(225, 66);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsColorWell21, EOViewLayout.MinYMargin);
        _nsView2.add(_nsColorWell21);
        _nsButton13.setSize(155, 17);
        _nsButton13.setLocation(21, 46);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton13, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton13);
        _nsColorWell24.setSize(30, 20);
        _nsColorWell24.setLocation(263, 88);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsColorWell24, EOViewLayout.MinYMargin);
        _nsView2.add(_nsColorWell24);
        _nsColorWell22.setSize(30, 20);
        _nsColorWell22.setLocation(263, 66);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsColorWell22, EOViewLayout.MinYMargin);
        _nsView2.add(_nsColorWell22);
        _nsButton15.setSize(95, 17);
        _nsButton15.setLocation(21, 68);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton15, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton15);
        _nsColorWell23.setSize(30, 20);
        _nsColorWell23.setLocation(225, 88);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsColorWell23, EOViewLayout.MinYMargin);
        _nsView2.add(_nsColorWell23);
        _nsColorWell17.setSize(30, 20);
        _nsColorWell17.setLocation(225, 22);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsColorWell17, EOViewLayout.MinYMargin);
        _nsView2.add(_nsColorWell17);
        _nsCustomView8.setSize(133, 22);
        _nsCustomView8.setLocation(301, 20);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsCustomView8, EOViewLayout.MinYMargin);
        _nsView2.add(_nsCustomView8);
        _nsCustomView9.setSize(133, 22);
        _nsCustomView9.setLocation(301, 42);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsCustomView9, EOViewLayout.MinYMargin);
        _nsView2.add(_nsCustomView9);
        _nsCustomView10.setSize(133, 22);
        _nsCustomView10.setLocation(301, 64);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsCustomView10, EOViewLayout.MinYMargin);
        _nsView2.add(_nsCustomView10);
        _nsCustomView11.setSize(133, 22);
        _nsCustomView11.setLocation(301, 86);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsCustomView11, EOViewLayout.MinYMargin);
        _nsView2.add(_nsCustomView11);
        _nsButton17.setSize(143, 17);
        _nsButton17.setLocation(223, 115);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton17, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton17);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Kontakty poza sieci\u0105:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _setFontForComponent(_nsTextField5, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField5.setEditable(false);
        _nsTextField5.setOpaque(false);
        _nsTextField5.setText("Status opisowy:");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField5.setSelectable(false);
        _nsTextField5.setEnabled(true);
        _nsTextField5.setBorder(null);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsButton6.setSize(141, 17);
        _nsButton6.setLocation(21, 90);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton6);
        _nsButton4.setSize(141, 17);
        _nsButton4.setLocation(21, 46);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton4);
        _nsButton3.setSize(141, 17);
        _nsButton3.setLocation(21, 24);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton3);
        _nsColorWell4.setSize(30, 20);
        _nsColorWell4.setLocation(205, 65);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell4, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell4);
        _nsColorWell5.setSize(30, 20);
        _nsColorWell5.setLocation(243, 65);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell5, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell5);
        _nsColorWell7.setSize(30, 20);
        _nsColorWell7.setLocation(243, 87);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell7, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell7);
        _nsColorWell3.setSize(30, 20);
        _nsColorWell3.setLocation(243, 43);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell3, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell3);
        _nsColorWell0.setSize(30, 20);
        _nsColorWell0.setLocation(205, 21);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell0);
        _nsButton5.setSize(141, 17);
        _nsButton5.setLocation(21, 68);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton5);
        _nsColorWell1.setSize(30, 20);
        _nsColorWell1.setLocation(243, 21);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell1, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell1);
        _nsColorWell8.setSize(30, 20);
        _nsColorWell8.setLocation(205, 109);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell8, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell8);
        _nsColorWell2.setSize(30, 20);
        _nsColorWell2.setLocation(205, 43);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell2, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell2);
        _nsColorWell9.setSize(30, 20);
        _nsColorWell9.setLocation(243, 109);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell9, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell9);
        _nsColorWell6.setSize(30, 20);
        _nsColorWell6.setLocation(205, 87);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell6, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell6);
        _nsButton7.setSize(178, 17);
        _nsButton7.setLocation(21, 112);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton7);
        _nsCustomView0.setSize(133, 22);
        _nsCustomView0.setLocation(289, 20);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView0);
        _nsCustomView1.setSize(133, 22);
        _nsCustomView1.setLocation(289, 42);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView1);
        _nsCustomView2.setSize(133, 22);
        _nsCustomView2.setLocation(289, 64);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView2, EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView2);
        _nsCustomView3.setSize(133, 22);
        _nsCustomView3.setLocation(289, 86);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView3, EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView3);
        _nsCustomView4.setSize(133, 22);
        _nsCustomView4.setLocation(289, 108);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsCustomView4, EOViewLayout.MinYMargin);
        _nsView1.add(_nsCustomView4);
        _nsButton9.setSize(102, 17);
        _nsButton9.setLocation(218, 137);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton9, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton9);
        _nsTextField5.setSize(132, 17);
        _nsTextField5.setLocation(21, 167);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField5);
        _nsColorWell14.setSize(30, 20);
        _nsColorWell14.setLocation(157, 166);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsColorWell14, EOViewLayout.MinYMargin);
        _nsView1.add(_nsColorWell14);
        _nsButton10.setSize(278, 17);
        _nsButton10.setLocation(155, 193);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton10, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton10);
        _nsTextField6.setSize(134, 17);
        _nsTextField6.setLocation(21, 192);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField6);
        _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Styl:");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("T\u0142o");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Wygaszaj obrazek:");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsButton1.setSize(73, 22);
        _nsButton1.setLocation(314, 106);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsTextField0.setSize(263, 19);
        _nsTextField0.setLocation(44, 107);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsButton8.setSize(141, 17);
        _nsButton8.setLocation(21, 84);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton8);
        _nsTextField1.setSize(42, 14);
        _nsTextField1.setLocation(313, 137);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField2.setSize(122, 17);
        _nsTextField2.setLocation(37, 134);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsSlider0.setSize(148, 21);
        _nsSlider0.setLocation(161, 134);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsSlider0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsSlider0);
        _nsCustomView7.setSize(133, 22);
        _nsCustomView7.setLocation(258, 42);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView7, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView7);
        _nsColorWell16.setSize(30, 20);
        _nsColorWell16.setLocation(174, 43);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsColorWell16, EOViewLayout.MinYMargin);
        _nsView0.add(_nsColorWell16);
        _nsColorWell15.setSize(30, 20);
        _nsColorWell15.setLocation(174, 21);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsColorWell15, EOViewLayout.MinYMargin);
        _nsView0.add(_nsColorWell15);
        _nsButton11.setSize(141, 17);
        _nsButton11.setLocation(21, 46);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton11, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton11);
        _nsCustomView6.setSize(133, 22);
        _nsCustomView6.setLocation(258, 20);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView6, EOViewLayout.MinYMargin);
        _nsView0.add(_nsCustomView6);
        _nsTextField3.setSize(107, 17);
        _nsTextField3.setLocation(40, 22);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _popup0.setSize(143, 26);
        _popup0.setLocation(165, 157);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsTextField4.setSize(38, 17);
        _nsTextField4.setLocation(121, 159);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField4);
        _nsTabView0.addTab("Okno", _nsView0);
        _nsTabView0.addTab("Status", _nsView1);
        _nsTabView0.addTab("Zdarzenia", _nsView2);
        _nsTabView0.addTab("Grupy", _nsView3);
        _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton18") == null) {
            _setFontForComponent(_nsButton18, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton17") == null) {
            _setFontForComponent(_nsButton17, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsCustomView11") == null) {
            _connect(_nsCustomView11, _nsColorWell24, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView11") == null) {
            _connect(_nsCustomView11, _nsColorWell23, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView10") == null) {
            _connect(_nsCustomView10, _nsColorWell22, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView10") == null) {
            _connect(_nsCustomView10, _nsColorWell21, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView9") == null) {
            _connect(_nsCustomView9, _nsColorWell20, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView9") == null) {
            _connect(_nsCustomView9, _nsColorWell19, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView8") == null) {
            _connect(_nsCustomView8, _nsColorWell18, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView8") == null) {
            _connect(_nsCustomView8, _nsColorWell17, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView7") == null) {
            _connect(_nsCustomView7, _nsColorWell16, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView7") == null) {
            _connect(_nsCustomView7, _nsColorWell16, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView6") == null) {
            _connect(_nsCustomView6, _nsColorWell15, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView6") == null) {
            _connect(_nsCustomView6, _nsColorWell15, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsButton16") == null) {
            _setFontForComponent(_nsButton16, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton15") == null) {
            _setFontForComponent(_nsButton15, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton14") == null) {
            _setFontForComponent(_nsButton14, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton13") == null) {
            _setFontForComponent(_nsButton13, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton12") == null) {
            _setFontForComponent(_nsButton12, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _setFontForComponent(_nsButton11, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton10") == null) {
            _setFontForComponent(_nsButton10, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _setFontForComponent(_nsButton9, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsCustomView5") == null) {
            _connect(_nsCustomView5, _nsColorWell13, "textShadowColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView5") == null) {
            _connect(_nsCustomView5, _nsColorWell12, "backgroundGradientColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView5") == null) {
            _connect(_nsCustomView5, _nsColorWell11, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView5") == null) {
            _connect(_nsCustomView5, _nsColorWell10, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField1.setEditable(false);
            _nsTextField1.setOpaque(false);
            _nsTextField1.setText("##%");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(false);
            _nsTextField1.setEnabled(true);
            _nsTextField1.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsSlider0") == null) {
            _setFontForComponent(_nsSlider0, "Helvetica", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField0.setEditable(false);
            _nsTextField0.setOpaque(true);
            _nsTextField0.setText("");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(false);
            _nsTextField0.setEnabled(false);
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 11, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _setFontForComponent(_nsButton8, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsCustomView4") == null) {
            _connect(_nsCustomView4, _nsColorWell9, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView4") == null) {
            _connect(_nsCustomView4, _nsColorWell8, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView3") == null) {
            _connect(_nsCustomView3, _nsColorWell7, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView3") == null) {
            _connect(_nsCustomView3, _nsColorWell6, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView2") == null) {
            _connect(_nsCustomView2, _nsColorWell5, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView2") == null) {
            _connect(_nsCustomView2, _nsColorWell4, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_nsCustomView1, _nsColorWell3, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_nsCustomView1, _nsColorWell2, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_nsCustomView0, _nsColorWell1, "backgroundColor");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_nsCustomView0, _nsColorWell0, "textColor");
        }

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _setFontForComponent(_nsButton7, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _setFontForComponent(_nsButton6, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsView4.getLayout() instanceof EOViewLayout)) { _nsView4.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(94, 26);
        _nsButton0.setLocation(235, 297);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView4.add(_nsButton0);
        _nsButton2.setSize(81, 26);
        _nsButton2.setLocation(336, 297);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView4.add(_nsButton2);
        _nsTabView0.setSize(464, 279);
        _nsTabView0.setLocation(-19, 11);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.MinYMargin);
        _nsView4.add(_nsTabView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView4.setSize(426, 333);
            _eoFrame0.setTitle("Panel");
            _eoFrame0.setLocation(131, 375);
            _eoFrame0.setSize(426, 333);
        }
    }
}
